import type { Palette } from "./palettes";
import type { DiagramFamily } from "./detector";

const TOOL_NAME = "Mermaid Theme Builder";
const TOOL_CREATOR = "OverKill Hill P³ / Jamie Hill";
const TOOL_URL = "https://overkillhill.com/projects/mermaid-theme-builder/";
const TOOL_VERSION = "0.2.0";

export interface ThemeOptions {
  palette: Palette;
  diagramFamily: DiagramFamily;
  theme?: "base" | "default" | "dark" | "forest" | "neutral";
  includeMetadata?: boolean;
}

export interface ThemeMetadata {
  themeName: string;
  themeId: string;
  createdWith: string;
  createdBy: string;
  toolVersion: string;
  toolUrl: string;
  generatedAt: string;
}

function buildThemeVars(palette: Palette): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const color of palette.colors) {
    vars[color.key] = color.value;
  }
  return vars;
}

function buildMetadataComments(meta: ThemeMetadata): string {
  return [
    `%% Theme: ${meta.themeName}`,
    `%% Theme ID: ${meta.themeId}`,
    `%% Created with: ${meta.createdWith} by ${meta.createdBy}`,
    `%% Tool URL: ${meta.toolUrl}`,
    `%% Tool Version: ${meta.toolVersion}`,
    `%% Generated: ${meta.generatedAt}`,
  ].join("\n");
}

export function generateThemedCode(originalCode: string, options: ThemeOptions): string {
  const { palette, includeMetadata = true } = options;

  const strippedCode = originalCode.replace(/%%\s*\{.*?\}.*?%%\s*\n?/gs, "").trimStart();

  const vars = buildThemeVars(palette);

  const varEntries = Object.entries(vars)
    .filter(([k]) => k !== "fontFamily")
    .map(([k, v]) => `"${k}": "${v}"`)
    .join(", ");

  const fontFamilyEntry = vars["fontFamily"] ? `"fontFamily": "${vars["fontFamily"]}"` : null;

  const themeVarsStr = [varEntries, fontFamilyEntry].filter(Boolean).join(", ");

  const initDirective = `%%{init: {"theme": "base", "themeVariables": {${themeVarsStr}}}}%%`;

  const meta: ThemeMetadata = {
    themeName: palette.name,
    themeId: palette.id,
    createdWith: TOOL_NAME,
    createdBy: TOOL_CREATOR,
    toolVersion: TOOL_VERSION,
    toolUrl: TOOL_URL,
    generatedAt: new Date().toISOString().replace("T", " ").slice(0, 16) + " UTC",
  };

  const metaBlock = includeMetadata ? buildMetadataComments(meta) + "\n" : "";

  return `${metaBlock}${initDirective}\n${strippedCode}`;
}

export function generateMarkdownExport(
  themedCode: string,
  paletteName: string,
  includeMetadata = true,
): string {
  const attribution = includeMetadata
    ? `\n<!-- ${TOOL_NAME} by ${TOOL_CREATOR} — ${TOOL_URL} -->`
    : "";
  return `# Mermaid Diagram — ${paletteName} Theme

\`\`\`mermaid
${themedCode}
\`\`\`
${attribution}
`;
}

export function generatePromptScaffold(
  palette: Palette,
  diagramFamily: DiagramFamily,
  includeMetadata = true,
): string {
  const familyName = diagramFamily === "unknown" ? "Mermaid" : diagramFamily;

  const colorLines = palette.colors
    .filter((c) => !["fontFamily", "edgeLabelBackground"].includes(c.key))
    .map((c) => `  - ${c.label}: \`${c.value}\``)
    .join("\n");

  const metaHeader = includeMetadata
    ? `<!-- Generated by ${TOOL_NAME} by ${TOOL_CREATOR} — ${TOOL_URL} -->\n\n`
    : "";

  return `${metaHeader}# Mermaid Diagram Prompt Scaffold — ${palette.name} Theme

## Instructions for AI

When generating ${familyName} diagrams, apply the following visual theme to ensure consistent styling.

## Required: Add this init directive at the top of EVERY diagram

\`\`\`
%%{init: {"theme": "base", "themeVariables": {${palette.colors
    .filter((c) => c.key !== "fontFamily")
    .map((c) => `"${c.key}": "${c.value}"`)
    .join(", ")}}}}%%
\`\`\`

## Theme Palette: ${palette.name}

${palette.description}

### Color Reference
${colorLines}
${palette.attribution ? `\n### Attribution\n${palette.attribution}\n` : ""}
## Rules

1. ALWAYS start the diagram with the \`%%{init:...}%%\` directive above — no exceptions.
2. Use \`${diagramFamily === "unknown" ? "flowchart TD" : diagramFamily === "flowchart" ? "flowchart TD" : diagramFamily}\` as the diagram type.
3. Keep node labels concise (under 60 characters each).
4. Do NOT add extra CSS or styling overrides — the init directive handles all visual styling.
5. If the diagram needs sub-graphs or clusters, use them — they inherit the theme automatically.

## Example Output Structure

\`\`\`mermaid
%%{init: {"theme": "base", "themeVariables": {"primaryColor": "${palette.colors.find((c) => c.key === "primaryColor")?.value || "#1a4f8a"}", ...}}}%%
${diagramFamily === "flowchart" || diagramFamily === "unknown" ? `flowchart TD
    A[Start] --> B[Process]
    B --> C{Decision}
    C -->|Yes| D[End]
    C -->|No| B` : `${diagramFamily}
    %% Your diagram here`}
\`\`\`

---
*Generated by ${TOOL_NAME} by ${TOOL_CREATOR} — ${TOOL_URL}*
`;
}
