import type { Palette } from "./palettes";
import type { DiagramFamily } from "./detector";

export interface ThemeOptions {
  palette: Palette;
  diagramFamily: DiagramFamily;
  theme?: "base" | "default" | "dark" | "forest" | "neutral";
}

function buildThemeVars(palette: Palette): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const color of palette.colors) {
    vars[color.key] = color.value;
  }
  return vars;
}

export function generateThemedCode(originalCode: string, options: ThemeOptions): string {
  const { palette } = options;

  const strippedCode = originalCode.replace(/%%\s*\{.*?\}.*?%%\s*\n?/gs, "").trimStart();

  const vars = buildThemeVars(palette);

  const varEntries = Object.entries(vars)
    .filter(([k]) => k !== "fontFamily")
    .map(([k, v]) => `"${k}": "${v}"`)
    .join(", ");

  const fontFamilyEntry = vars["fontFamily"] ? `"fontFamily": "${vars["fontFamily"]}"` : null;

  const themeVarsStr = [varEntries, fontFamilyEntry].filter(Boolean).join(", ");

  const initDirective = `%%{init: {"theme": "base", "themeVariables": {${themeVarsStr}}}}%%`;

  return `${initDirective}\n${strippedCode}`;
}

export function generateMarkdownExport(themedCode: string, paletteName: string): string {
  return `# Mermaid Diagram — ${paletteName} Theme

\`\`\`mermaid
${themedCode}
\`\`\`

<!-- Generated by Mermaid Theme Builder -->
`;
}

export function generatePromptScaffold(palette: Palette, diagramFamily: DiagramFamily): string {
  const familyName = diagramFamily === "unknown" ? "Mermaid" : diagramFamily;

  const colorLines = palette.colors
    .filter((c) => !["fontFamily", "edgeLabelBackground"].includes(c.key))
    .map((c) => `  - ${c.label}: \`${c.value}\``)
    .join("\n");

  return `# Mermaid Diagram Prompt Scaffold — ${palette.name} Theme

## Instructions for AI

When generating ${familyName} diagrams, apply the following visual theme to ensure consistent styling.

## Required: Add this init directive at the top of EVERY diagram

\`\`\`
%%{init: {"theme": "base", "themeVariables": {${palette.colors
    .filter((c) => c.key !== "fontFamily")
    .map((c) => `"${c.key}": "${c.value}"`)
    .join(", ")}}}}%%
\`\`\`

## Theme Palette: ${palette.name}

${palette.description}

### Color Reference
${colorLines}

## Rules

1. ALWAYS start the diagram with the \`%%{init:...}%%\` directive above — no exceptions.
2. Use \`${diagramFamily === "unknown" ? "flowchart TD" : diagramFamily === "flowchart" ? "flowchart TD" : diagramFamily}\` as the diagram type.
3. Keep node labels concise (under 60 characters each).
4. Do NOT add extra CSS or styling overrides — the init directive handles all visual styling.
5. If the diagram needs sub-graphs or clusters, use them — they inherit the theme automatically.

## Example Output Structure

\`\`\`mermaid
%%{init: {"theme": "base", "themeVariables": {"primaryColor": "${palette.colors.find((c) => c.key === "primaryColor")?.value || "#1a4f8a"}", ...}}}%%
${diagramFamily === "flowchart" || diagramFamily === "unknown" ? `flowchart TD
    A[Start] --> B[Process]
    B --> C{Decision}
    C -->|Yes| D[End]
    C -->|No| B` : `${diagramFamily}
    %% Your diagram here`}
\`\`\`

---
*Generated by Mermaid Theme Builder — paste this scaffold into your AI prompt to maintain visual consistency.*
`;
}
